### ISSUE TITLE
banaliser les variables de couleurs

### ISSUE THREAD

**Issue by alemoine** [ecedi/edonate#16]
Faire en sorte que les couleurs du site soient plus simple à modifier.

**Comment by alemoine** [comment]
nom des couleurs changées sur la branche "feature-fe-aml"

reste à faire : simplifier l'ensemble en vue d'une duplication. Ex : différencier la couleur des titres et fonds

**Comment by meshenka** [comment]
nom des couleurs mergé car j'ai mergé la branche feature-fe-aml ici 461487e955a3f0ea02df904e82965cb75abd959b
