### ISSUE TITLE
Fautes d'orthographes

### ISSUE THREAD

**Issue by bdautun-ecedi** [ecedi/edonate#19]
* accueil s'écrit accueil, pas acceuil.
* Dans "Votre application ECollecte n'est pas configurer pour obtenir les statistiques Google Analytics" configurer doit s'écrire configurée

**Comment by meshenka** [comment]
fixed in https://github.com/ecedi/edonate/commit/59cf04a9f125bf544ef1841d5716cda0b4c01d0f
