### ISSUE TITLE
background Image

### ISSUE THREAD

**Issue by meshenka** [ecedi/edonate#4]
```
 body {
                background:url(http://donate.loc/media/cache/layout_background/5350028ec0411.png) no-repeat center top #fff; background-size: 100% 496px;
                }
```
a transformé en

background-image:url(http://donate.loc/media/cache/layout_background/5350028ec0411.png)

et mettre le reste dans les styles

**Comment by alemoine** [comment]
fait sur la branche  "feature-fe-aml"
